name: Trigger auto deployment for container-app-3w3f6cbkhz3wc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3w3f6cbkhz3wc-AutoDeployTrigger-027958d4-4815-4dc9-86d8-d10d94f94e75.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3W3F6CBKHZ3WC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3W3F6CBKHZ3WC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3W3F6CBKHZ3WC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3W3F6CBKHZ3WC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3W3F6CBKHZ3WC_REGISTRY_PASSWORD }}
          containerAppName: container-app-3w3f6cbkhz3wc
          resourceGroup: appspacesragapp9d8c82e7
          imageToBuild: default/container-app-3w3f6cbkhz3wc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


